version: '3.8'
services:
  ray:
    image: rayproject/ray:latest
    command: ["ray", "start", "--head"]
    ports:
      - "8265:8265"

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"

  app:
    build: .
    depends_on:
      - ray
      - qdrant
    ports:
      - "7860:7860"
